# Generated by Django 5.2 on 2025-04-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'ETANOL'), (2, 'DIESEL'), (3, 'FLEX'), (4, 'FLEX'), (5, 'GASOLINA')], verbose_name='Combustível')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.SmallIntegerField(choices=[(1, 'CHEVROLET'), (2, 'FORD'), (3, 'FIAT'), (4, 'VOLKSWAGEN'), (5, 'HONDA'), (6, 'TOYOTA'), (7, 'NISSAN'), (8, 'HYUNDAI'), (9, 'KIA'), (10, 'RENAULT'), (11, 'PEUGEOT'), (12, 'CITROËN'), (13, 'JEEP'), (14, 'CHRYSLER'), (15, 'DODGE'), (16, 'SUBARU'), (17, 'MITSUBISHI'), (18, 'MAZDA'), (19, 'LAND ROVER'), (20, 'JAGUAR')], verbose_name='Marca')),
                ('cor', models.SmallIntegerField(choices=[(1, 'PRETO'), (2, 'BRANCO'), (3, 'PRATA'), (4, 'VERMELHO'), (5, 'AZUL'), (6, 'VERDE'), (7, 'AMARELO'), (8, 'LARANJA'), (9, 'ROXO'), (10, 'MARROM')], verbose_name='Cor')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
        ),
    ]
