# Generated by Django 5.2 on 2025-04-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['modelo'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AlterModelTable(
            name='veiculo',
            table='veiculos',
        ),
    ]
