# Generated by Django 5.2 on 2025-05-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_alter_veiculo_options_alter_veiculo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.SmallIntegerField(choices=[('', 'Selecione o combustível'), (1, 'ETANOL'), (2, 'DIESEL'), (3, 'FLEX'), (4, 'GASOLINA')], verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.SmallIntegerField(choices=[('', 'Selecione a cor'), (1, 'PRETO'), (2, 'BRANCO'), (3, 'PRATA'), (4, 'VERMELHO'), (5, 'AZUL'), (6, 'VERDE'), (7, 'AMARELO'), (8, 'LARANJA'), (9, 'ROXO'), (10, 'MARROM')], verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.SmallIntegerField(choices=[('', 'Selecione a marca'), (1, 'CHEVROLET'), (2, 'FORD'), (3, 'FIAT'), (4, 'VOLKSWAGEN'), (5, 'HONDA'), (6, 'TOYOTA'), (7, 'NISSAN'), (8, 'HYUNDAI'), (9, 'KIA'), (10, 'RENAULT'), (11, 'PEUGEOT'), (12, 'CITROËN'), (13, 'JEEP'), (14, 'CHRYSLER'), (15, 'DODGE'), (16, 'SUBARU'), (17, 'MITSUBISHI'), (18, 'MAZDA'), (19, 'LAND ROVER'), (20, 'JAGUAR')], verbose_name='Marca'),
        ),
    ]
