# Generated by Django 5.2 on 2025-05-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_alter_veiculo_combustivel_alter_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='veiculo/fotos', verbose_name='Foto'),
        ),
    ]
