# Generated by Django 5.2 on 2025-05-21 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
        ('veiculo', '0004_veiculo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='veiculo.veiculo'),
            preserve_default=False,
        ),
    ]
